services:
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    networks:
      - microservices-network

  auth-service:
    build: ./auth-service
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
    networks:
      - microservices-network

  peer-management-service:
    build: ./peer-management-service
    ports:
      - "8086:8086"
    depends_on:
      - service-registry
    networks:
      - microservices-network

  file-transfer-service:
    build: ./file-transfer-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
    networks:
      - microservices-network

  file-metadata-service:
    build: ./file-metadata-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
